config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :photos
  resources :users

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	attachment :image, content_type: ["image/jpeg", "image/png"] 

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to users_path
      # redirect_to(request.referrer || root_path)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to photos_path
  	else		
      redirect_to new_user_session_path
  	end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @photos = policy_scope(Photo.all)
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    if @photo.save
      redirect_to @photo, notice: 'Photo was successfully created.'
    else
      render :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: 'Photo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_url, notice: 'Photo was successfully destroyed.'
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:name, :image, :public_view)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
  	params.require(:user).permit(:name, :surname, :email, :mobile_number, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :create, :destroy]

  def index
    @users = policy_scope(User.all)
    # @users = User.all
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
    @users = policy_scope(@user)
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new 
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    authorize @user
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :surname, :email, :mobile_number, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'PHOTOS', photos_path %><span class="sr-only">(current)</span></li>
          <li><%= link_to 'USERS', users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><p>Welcome <b><%= current_user.email %></b><span class="btn btn-default navbar-btn"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></span></p></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :photo_name %>
  </div>
  <div class="field">
    <%= form.attachment_field :image %>
  </div>
    <div class="field">
    <%= form.label :public_view %>
    <%= form.check_box :public_view %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class= "container">
	<h1>Editing Photo</h1>

	<%= render 'form', photo: @photo %>

	<span class="btn btn-default"><%= link_to 'Show', @photo %></span>
	<span class="btn btn-default"><%= link_to 'Back', photos_path %></span>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>
<span class="btn btn-default navbar-btn"><%= link_to 'New Photo', new_photo_path %></span>
<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Image</th>
        <th>Public</th>
        <th>Owner</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @photos.each do |photo| %>
        <tr>
          <td><%= photo.name %></td>
          <td><%= image_tag(attachment_url(photo, :image, :fill, 100, 100)) %></td>
          <td><%= photo.public_view %></td>
          <td><%= photo.user == current_user ? "Me" : photo.user.name %></td>
          <% if policy(photo).show? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Show', photo %></td>
          <% end %>
          <% if policy(photo).edit? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Edit', edit_photo_path(photo) %></td>
          <% end %>
          <% if policy(photo).destroy? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<span class="btn btn-default"><%= link_to 'Back', photos_path %></span>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div>
		<p>
		  <strong>Name:</strong>
		  <%= @photo.name %>
		</p>
	</div>
	<div>
		<p>
		  <strong>Image:</strong>
		  <%= image_tag attachment_url(@photo, :image, :fill, 100, 100) %>
		</p>
	</div>
	<div>
		<p>
			<strong>Public:</strong>
			<%= @photo.public_view %>
		</p>
	<span class="btn btn-default"><%= link_to 'Edit', edit_photo_path(@photo) %> </span>
	<span class="btn btn-default"><%= link_to 'Back', photos_path %></span>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label "Name"%>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label "Surname"%>
    <%= form.text_field :surname %>
  </div>
  <div class="field">
    <%= form.label "Email"%>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label "Mobile number"%>
    <%= form.text_field :mobile_number %>
  </div>
  <% if policy(user).admin? %>
    <div class="field">
      <%= form.label "Admin"%>
      <%= form.check_box :admin  %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class= "container">
	<legend>Editing User</legend>

	<%= render 'form', user: @user %>
	<span class="btn btn-default"><%= link_to 'Show', @user %></span> 
	<span class="btn btn-default"><%= link_to 'Back', users_path %></span>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div>
  <% if policy(current_user).new? %>
    <span class="btn btn-default navbar-btn"><%= link_to 'New User', new_user_path %></span>(Only an admin can create a new user after loging in, Non admin can't see this button)
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Email</th>
        <th>Mobile number</th>
        <th>Admin</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td><%= user.email %></td>
          <td><%= user.mobile_number %></td>
          <td><%= user.admin %></td>
          <% if policy(user).show? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Show', user %></td>
          <% end %>
          <% if policy(user).edit? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Edit', edit_user_path(user) %></td>
          <% end %>
          <% if policy(user).destroy? %>
            <td class="btn btn-default navbar-btn"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/users/new.html.erb
<div class= "container">
	<legend>Create a new User</legend>
	<%= render 'form', user: @user %>
</div>

<span class="btn btn-default"><%= link_to 'Back', users_path %></span>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "container">
	<div>
		<p><b>Name:</b> <%= @user.name %></p>
	</div>

	<div>
		<p><b>Surname:</b> <%= @user.surname %></p>
	</div>

	<div>
		<p><b>Email:</b> <%= @user.email %></p>
	</div>

	<div>
		<p><b>Mobile number:</b> <%= @user.mobile_number %></p>
	</div>
	<div>
		<p><b>Admin:</b> <%= @user.admin %></p>
	</div>
	<div>
	  <% if policy(@user).update? %>
	  	<span class="btn btn-default"><%= link_to 'Edit', edit_user_path(@user) %></span>
	  <% end %>
	  <span class="btn btn-default"><%= link_to 'Back', users_path %></span>
	</div>
</div>